# Exported from Render on 2024-11-02T18:39:44Z
services:
  - type: web
    name: forex-explorer
    runtime: image
    image:
      url: docker.io/surarohith/forex-explorer:latest
    plan: free
    region: oregon
version: "1"
